services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: checkin-frontend
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - checkin_net
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: checkin-nginx
    networks:
      - checkin_net
    environment:
      - TZ=Asia/Seoul
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend

networks:
  checkin_net:
    driver: bridge

